### ISSUE TITLE
variable not defined

### ISSUE THREAD

**Issue by fnattino** [GO-Eratosthenes/dhdt#107]
the variable `sqroot_sq` in the function `linear_reflectance_surface_estimation` in `dhdt/processing/photoclinometric_functions.py` is not defined. It is supposed to be `sqroot_pq`?

https://github.com/GO-Eratosthenes/dhdt/blob/e397ef7d7bbe418f360277e4334252d398c87ffe/dhdt/processing/photoclinometric_functions.py#L200C46-L200C46

**Comment by dicaearchus** [comment]
resolved with #109
