### ISSUE TITLE
Green vs Blue band in entropy shadow enhancement method

### ISSUE THREAD

**Issue by fnattino** [GO-Eratosthenes/dhdt#21]
Hi @dicaearchus, a question about the "entropy" shadow enhancement method. I see that it works with only two visible bands plus NIR. From the docstring of the `entropy_shade_removal` function I seem to get that the function should take the highest-frequency band as first input argument, which for the 10m bands should be the Blue band ("B02")? But instead the Green band ("B03") seems to be passed over here:    

https://github.com/GO-Eratosthenes/start-code/blob/1ebf1b59e0d78d4bd4c00ce1a2126755f25b2a0b/eratosthenes/preprocessing/shadow_transforms.py#L95

Is this intended and working better for some reasons?

**Comment by dicaearchus** [comment]
The Green band seems to work better than the Blue band, this might be due to the atmospheric absorption. Furthermore, the original method used RGB, while here the Near Infrared band is used.
