### ISSUE TITLE
Undefined `get_stack_out_of_dir`

### ISSUE THREAD

**Issue by fnattino** [GO-Eratosthenes/dhdt#28]
Function `get_stack_out_of_dir` is called here (`dhdt/processing/coupling_tools.py`) but not declared:

https://github.com/GO-Eratosthenes/dhdt/blob/277d6550c59c12b0e88e7cfd88158f09211cc0a6/dhdt/processing/coupling_tools.py#L381

**Comment by dicaearchus** [comment]
This function was for multispectral data, but this is not resolved via dataframes of the different instruments within the read_geo_image
