### ISSUE TITLE
`breakpoint` left in `coupling_tools.py`

### ISSUE THREAD

**Issue by fnattino** [GO-Eratosthenes/dhdt#29]
A `breakpoint` was left here  (`dhdt/processing/coupling_tools.py`)

https://github.com/GO-Eratosthenes/dhdt/blob/277d6550c59c12b0e88e7cfd88158f09211cc0a6/dhdt/processing/coupling_tools.py#L872

**Comment by dicaearchus** [comment]
this is not the case anymore
