### ISSUE TITLE
Masking data in `match_pair`

### ISSUE THREAD

**Issue by fnattino** [GO-Eratosthenes/dhdt#36]
`match_pair` from `dhdt.processing.coupling_tools` deals with arrays and masks, which can be passed as independent objects or as masked arrays. The function assumes True values in the mask stands for valid points, but this is the opposite of the convention of masked arrays. This should be fixed or/and the chosen convention should be explained in the docs.

**Comment by dicaearchus** [comment]
Old issue, this has been resolved some time ago and is stated in the documentation.
