### ISSUE TITLE
DEM module

### ISSUE THREAD

**Issue by fnattino** [GO-Eratosthenes/dhdt#60]
Fetch, retile and merge Copernicus DEM. 

Current module: `dhdt/auxiliary/handler_copernicusdem.py`

Try to clean up use of `ftps` (stale library, no longer updated), use something else? (see #48 )

Part of #52

**Comment by fnattino** [comment]
See also #22  for a script related to this retiling

**Comment by fnattino** [comment]
DEM should be available also from here: https://registry.opendata.aws/copernicus-dem/

**Comment by cpranav93** [comment]
[ftputil](https://ftputil.sschwarzer.net/documentation) builds on the python ftplib to provide high level commands for ftp. Could be useful here.

**Comment by fnattino** [comment]
If we manage to get data from AWS might actually be better, since no registration is required (the FTP server does require creating an account)

**Comment by cpranav93** [comment]
For that, I saw this [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-example-download-file.html) example which seems relevant. I will try it out and see how it works.

**Comment by fnattino** [comment]
Here they discuss how to setup a STAC catalog for that dataset. Not relevant here, but it might provide info on how to get access to files via "plain" HTTP URLs: https://discourse.pangeo.io/t/creating-searchable-stac-catalog-from-cogs-in-s3/3205

**Comment by fnattino** [comment]
Instructions on how to access public AWS bucket via HTTP: https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html

**Comment by cpranav93** [comment]
PR #75 addresses this issue.

**Comment by fnattino** [comment]
Closed by #75 and #79
