### ISSUE TITLE
MGRS tiling module

### ISSUE THREAD

**Issue by fnattino** [GO-Eratosthenes/dhdt#61]
Create a module to:
* fetch the Sentinel-2 tiling scheme from Copernicus (see link to KML file provided [here](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-2/data-products)).
* clean geometries (extract bounds from geometry arrays). 
* save it as easier-to-handle format (geojson).

Module not yet present, to be added to `dhdt/auxiliary/handler_mgrs.py`

Part of #52

**Comment by fnattino** [comment]
Current code snippet:

```python
import os

import geopandas as gpd

from fiona.drvsupport import supported_drivers

from dhdt.auxilary.handler_rgi import create_rgi_raster
from dhdt.generic.handler_www import get_file_from_www


supported_drivers['LIBKML'] = 'rw'


SENTINEL2_TILING_GRID_URL = "https://sentinels.copernicus.eu/documents/247904/1955685/S2A_OPER_GIP_TILPAR_MPC__20151209T095117_V20150622T000000_21000101T000000_B00.kml"


def convert_tiling_kml_to_geojson():
    get_file_from_www(SENTINEL2_TILING_GRID_URL, dump_dir="../../data")
    _, filename = os.path.split(SENTINEL2_TILING_GRID_URL)
    df = gpd.read_file(f'../../data/{filename}', driver="LIBKML")
    df["geometry"] = df["geometry"].apply(lambda x: x.geoms[0])
    df.to_file('../../data/sentinel2_tiles_world.geojson')


if __name__ == "__main__":
    convert_tiling_kml_to_geojson()
```

**Comment by fnattino** [comment]
@rogerkuou do you want to start with this?

**Comment by rogerkuou** [comment]
notes: geojson file is required as an input for `dhdt.generic.handler_sentinel2.get_geom_for_tile_code`

See [this file](https://github.com/GO-Eratosthenes/dhdt/blob/master/dhdt/generic/handler_sentinel2.py)
