### ISSUE TITLE
Coastal module

### ISSUE THREAD

**Issue by fnattino** [GO-Eratosthenes/dhdt#62]
Fetch, rasterise and retile coastal data  (`GSHHS_f_L1.geojson`).

Current module: `dhdt/auxiliary/handler_coastal.py`

Part of #52

**Comment by dicaearchus** [comment]
Resolved in [47c3d19](https://github.com/GO-Eratosthenes/dhdt/commit/47c3d19d517633e93cd83336837cf11dd259e5ea)
