### ISSUE TITLE
MGRS-related functions

### ISSUE THREAD

**Issue by fnattino** [GO-Eratosthenes/dhdt#69]
The following functions requires the MGRS tiling GeoJSON. The default location where they should look for the file should be the same default location where this is downloaded (`./data/MGRS` ?):

* https://github.com/GO-Eratosthenes/dhdt/blob/df2a72fca0d9e7b0ad175f8b8a0a228e369fb36d/dhdt/generic/handler_sentinel2.py#L162
* https://github.com/GO-Eratosthenes/dhdt/blob/df2a72fca0d9e7b0ad175f8b8a0a228e369fb36d/dhdt/generic/handler_sentinel2.py#L196
* https://github.com/GO-Eratosthenes/dhdt/blob/df2a72fca0d9e7b0ad175f8b8a0a228e369fb36d/dhdt/generic/handler_sentinel2.py#L254

They could be moved to `dhdt/auxiliary/handler_mgrs.py`, together with the function that downloads and convert the KML tiling file.

**Comment by rogerkuou** [comment]
Thx! I will pick this up
